apiVersion: backstage.io/v1alpha1 
kind: Component
metadata: 
  name: exemplo_tutorial 
  annotations: 
    backstage.io/techdocs-ref: url:https://github.com/Matheus-Melo-dos-Santos/backstage/blob/main/docs/index.md
spec: 
  type: service 
  lifecycle: production 
  owner: group:exemplo_dono 

  system: systema_desejado 

