apiVersion: backstage.io/v1alpha1 
kind: Component
metadata: 
  name: meu-servico 
  annotations: 
    backstage.io/techdocs-ref: dir:. 
spec: 
  type: service 
  lifecycle: production 
  owner: group:exemplo_dono 
  system: systema_desejado 